### ISSUE TITLE
Discussing Types of Questions for the Questionnaire Interface

### ISSUE THREAD

**Issue by xlai** [xlai/dosefinderhub#6]
**Feature Overview**
We need to define and discuss the types of questions that will be included in the questionnaire interface for the DoseFinderHub project. This involves understanding the information that needs to be collected from the users to determine the likelihood/suitability of the dose-finding methods and to profile the best methods for the trial design/conduct.

**Current Status**
We have identified a review article in relation to the questionnaire. 

**Sub-issues/Tasks**

- [x] Identify the key information to be collected from users.
- [x] Determine the format of the questions (e.g., multiple-choice, open-ended)
- [x] Develop a list of potential questions.
- [ ] Review and revise the questions with stakeholders (if applicable).
- [ ] Integrate the finalized questions into the UI development process.

**Related Documentation**
Article in question can be found here [Early-Phase Oncology Trials: Why So Many Designs? ](https://ascopubs.org/doi/full/10.1200/JCO.21.02493)

**Comment by jakeholton** [comment]
RE: review and revise the questions with stakeholders - do you have a plan for this @xlai? Who do you have in mind to review?

**Comment by xlai** [comment]
> RE: review and revise the questions with stakeholders - do you have a plan for this @xlai? Who do you have in mind to review?

This will be part of the second iteration of the question bank so don't worry about it for now. However we will 

1. present our prototype at the first instance after Christina's return (from the point of view of a domain expert), and 
2.  Demo this to clinicians (users) if we have time.
